# fly.toml app configuration file generated for yoyos-amazing-bingo on 2024-11-28T14:11:00+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yoyos-amazing-bingo'
primary_region = 'syd'
swap_size_mb = 512

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
