import type { Metadata } from "next";

import { geistMono, geistSans } from "@/styles/fonts";

import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.className} antialiased`}
      >
        <main className="mx-auto flex h-dvh w-full flex-col justify-between p-8 md:max-w-2xl lg:max-w-4xl xl:max-w-5xl">
          {children}
        </main>
      </body>
    </html>
  );
}
